name: SimpleUserPerms
main: simpleuserperms.SimpleUserPerms
version: 1.0
author: _Shevchik_
load: STARTUP
softdepend: [Vault]
loadbefore: [WEPIFToVault]
commands:
  simpleuserperms:
    description: All SimpleUserPerms commands
    usage: Invalid command